[package]
name = "demo-blockchain"
version = "0.1.0"
authors = ["ruziev.dev"]
edition = "2021"


[dependencies]
time = "0.1.38"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sha2 = "0.7.0"
indicatif = "0.16.2"